[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.32/platform-espressif32.zip
platform_packages =
    framework-arduinoespressif32-libs @ https://github.com/bmorcelli/esp32-arduino-lib-builder/releases/download/idf-release_v5.5/esp32-arduino-libs-20251001-233155.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
extra_scripts = post:support_files/merge.py

lib_deps =
    moononournation/GFX Library for Arduino @ 1.5.0


# Common flags for all MiniTV builds
[minitv_common]
build_flags = 
    -D MENU_TITLE='"CYD Mini TV"'
    -D SCREEN_ROTATION=1
    -D USE_MCP23017

# Common flags for all Handheld builds
[handheld_common]
build_flags = 
    -D MENU_TITLE='"CYD Handheld"'
    -D SCREEN_ROTATION=3
    -D USE_PCF8575

[env:minitv-cyd2usb]
build_flags = 
    ${minitv_common.build_flags}
    -D BOARD_CYD2USB
    -D CORE_DEBUG_LEVEL=0

[env:minitv-cyd]
build_flags = 
    ${minitv_common.build_flags}
    -D BOARD_CYD
    -D CORE_DEBUG_LEVEL=0

[env:handheld-cyd2usb]
build_flags = 
    ${handheld_common.build_flags}
    -D BOARD_CYD2USB
    -D CORE_DEBUG_LEVEL=0

[env:handheld-cyd]
build_flags = 
    ${handheld_common.build_flags}
    -D BOARD_CYD
    -D CORE_DEBUG_LEVEL=0
